### ISSUE TITLE
worker is trying to work on a nil image

### ISSUE THREAD

**Issue by oren** [cube2222/Blog#1]
I am trying to run the microservices project and it looks like the worker is trying to do work on image that is nil. I had to add check for nil to the worker but it looks like now the worker never picks up any work:

``` go
if myImage == nil {
  continue
}                                                                                               

myImage = doWorkOnImage(myImage)
```

here is my repo with steps to reprocude in the readme:
https://github.com/oren/Blog/tree/master/Microservice%20architecture

**Comment by cube2222** [comment]
Could you please post a file with which you have this problem? Also please tell me what browser & OS you are using.

I was having this problem when I was testing 2000/3000 concurrent connections, but usually on a windows machine. I suppose it was happening due to only partly filled in image data (missing pixels). I'll look into it.

**Comment by cube2222** [comment]
I think I have just corrected it. The problem was that with sufficient load, a Task was created but not saved to the storage.Which means that we worked on a nil image. I changed the code a little bit so this case gets handled. 

Your problem I think, (why it happens every time and is replicable), is that your image storage microservice needs sudo privileges to save the images to the tmp/smthing directory. Also, it may be needed that you manually create the working and finished directories in the tmp directory.

**Comment by oren** [comment]
first about my environment - I am on ubuntu 15.10 and since the frontend is running on port 80 I had to run it with sudo. i tried changing it to port 3004 but it didn't make any difference. the image i am uploading is http://strabo.com/gallery/albums/wallpaper/foo_wallpaper.sized.jpg

I merged your commit into my fork and nothing crashes now.

first thing to note is I see the following messages in the console:

```
invalid character 'E' looking for beginning of value
Waiting 2 second timeout...
invalid character 'E' looking for beginning of value
Waiting 2 second timeout...
invalid character 'E' looking for beginning of value
Waiting 2 second timeout...
```

after uploading the image, the browser's url changes to http://127.0.0.1/submitTask
and i see `Error:<nil>` in the html page.

looking at the tasks storage looks good as well:

```
curl localhost:3001/list
0 :  id: 0  state: 1
 curl localhost:3001/list
0 :  id: 0  state: 2
```

but /tmp is empty. is there anything else i should curl or try to help me in troubleshooting this?

**Comment by cube2222** [comment]
It's the fault of the image. This worker is built to only work on png files. If you want to implement jpg you need to create another case/ use the jpg library. I used the png library. Also, as I wrote, create a "working" and "finished" folder in your tmp directory, and launch the storage microservice using sudo, as it probably doesn't have permission to use the tmp directory.

**Comment by oren** [comment]
the images i use are .jpg. after creating the 2 folders in my /tmp i see all the jpg files in the 'working' directory but they stay there.
also the /list show me the following:

```
curl localhost:3001/list
0 :  id: 0  state: 1
1 :  id: 1  state: 1
2 :  id: 2  state: 1
```

Here is an example of an image: https://upload.wikimedia.org/wikipedia/commons/b/b4/JPEG_example_JPG_RIP_100.jpg

**Comment by cube2222** [comment]
As I said, the worker can't do anything with them, as we used the PNG library, so only PNG images will get modified. You have to use the jpg library if you want jpgs.

**Comment by oren** [comment]
works now! I see the original image in '/tmp/working' and the processed one in '/tmp/finished'. Thank you!
